import { useState, useEffect, useCallback, useRef } from 'react'

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:3001"

export type NotificationType = 'payment' | 'invoice' | 'system' | 'security'

export interface Notification {
  id: string
  type: NotificationType
  title: string
  message: string
  status: 'unread' | 'read'
  created_at: string
}

export interface ToastNotification {
  id: string
  type: NotificationType
  title: string
  message: string
}

type ToastListener = (notif: ToastNotification) => void
const toastListeners: ToastListener[] = []

export const dispatchRealtimeUpdate = (type: string) => {
  const event = new CustomEvent('merca-realtime-update', { detail: { type } });
  window.dispatchEvent(event);
};

export const notifyToast = (notif: ToastNotification) => {
  toastListeners.forEach(fn => fn(notif))
}

export const onToast = (fn: ToastListener) => {
  toastListeners.push(fn)
  return () => {
    const idx = toastListeners.indexOf(fn)
    if (idx > -1) toastListeners.splice(idx, 1)
  }
}

const POLL_INTERVAL_MS = 30_000

export function useNotifications() {
  const [notifications, setNotifications] = useState<Notification[]>([])
  const [loading, setLoading] = useState(true)

  // Keeps track of seen notification IDs
  const seenIds = useRef<Set<string>>(new Set())
  const isInitialLoad = useRef(true) // TRACK INITIAL LOAD

  const token = localStorage.getItem('token')
  const headers = { Authorization: `Bearer ${token}` }

  const fetchNotifications = useCallback(async (isPolling = false) => {
    try {
      const res = await fetch(`${API_URL}/api/notifications`, { headers })
      if (!res.ok) return
      const data: Notification[] = await res.json()

      // Only show toasts if it's polling AND not the very first page boot-up
      if (isPolling && !isInitialLoad.current) {
        const newUnread = data.filter(
          n => n.status === 'unread' && !seenIds.current.has(n.id)
        )
        newUnread.forEach(n => {
          notifyToast({ id: n.id, type: n.type, title: n.title, message: n.message })

          if (n.type === 'payment' || n.type === 'invoice') {
            dispatchRealtimeUpdate(n.type);
          }
        })
      }

      // Populate seenIds on every fetch so we remember them
      data.forEach(n => seenIds.current.add(n.id))
      setNotifications(data)
    } catch (err) {
      console.error('Failed to fetch notifications', err)
    } finally {
      setLoading(false)
      isInitialLoad.current = false // Initial load complete
    }
  }, [])

  const markAsRead = async (id: string) => {
    await fetch(`${API_URL}/api/notifications/${id}/read`, {
      method: 'PATCH', headers,
    })
    setNotifications(prev => prev.map(n => n.id === id ? { ...n, status: 'read' } : n))
  }

  const markAllAsRead = async () => {
    await fetch(`${API_URL}/api/notifications/read-all`, {
      method: 'PATCH', headers,
    })
    setNotifications(prev => prev.map(n => ({ ...n, status: 'read' as const })))
  }

  const createNotification = async (type: NotificationType, title: string, message: string) => {
    const res = await fetch(`${API_URL}/api/notifications`, {
      method: 'POST',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ type, title, message }),
    })

    if (res.ok) {
      const data = await res.json();
      // Ensure we use the exact UUID generated by the backend database
      seenIds.current.add(data.id)
      notifyToast({ id: data.id, type, title, message })
    }
    await fetchNotifications(false)
  }

  useEffect(() => {
    fetchNotifications(false)
  }, [fetchNotifications])

  useEffect(() => {
    const interval = setInterval(() => {
      fetchNotifications(true)
    }, POLL_INTERVAL_MS)
    return () => clearInterval(interval)
  }, [fetchNotifications])

  const unreadCount = notifications.filter(n => n.status === 'unread').length

  return { notifications, loading, unreadCount, markAsRead, markAllAsRead, createNotification, refetch: fetchNotifications }
}